repo:
 image: debian:jessie
 volumes:
   - $PWD:/opt/repo
# command: /bin/true
opendj:
 image: kimdane/opendj
 volumes_from:
  - repo
#Persistence volumes: #Persistence
#Persistence  - $PWD/persistence/opendj_data:/opt/opendj/instances/instance1 #Persistence
openam:
 image: kimdane/openam
 links:
  - opendj:opendj
 volumes_from:
  - repo
postgres:
 image: postgres
 environment:
  - POSTGRES_PASSWORD=openidm
  - POSTGRES_USER=openidm
#Persistence  - PGDATA=/usr/local/postgresql/data/pgdata #Persistence
 volumes: 
  - $PWD/postgres:/docker-entrypoint-initdb.d
 #volumes_from:
 # - repo
#Persistence  - $PWD/persistence/pgdata:/usr/local/postgresql/data #Persistence
openidm:
 image: kimdane/openidm
 links:
  - opendj:opendj
  - postgres:postgres
 volumes_from:
  - repo
#Persistence volumes: #Persistence
#Persistence  - $PWD/persistence/openidm:/opt/openidm #Persistence
iam.example.com:
 #container_name: iam.example.com
 image: kimdane/haproxy-iam
 volumes:
   - $PWD/ssl:/etc/ssl
 links:
  - opendj:opendj
  - openidm:openidm
  - openam:openam-svc-a
 restart: always
 ports: 
  - 389:389/tcp
  - 636:636/tcp
  - 80:80/tcp
  - 443:443/tcp
ssoconfig:
 volumes_from:
  - repo
 image: kimdane/ssoconfig
 links:
  - opendj:opendj
  - openam:openam-svc-a
